#Mysql Container
mysql:
 image: mysql
 container_name: mysql
 hostname: mysql
 volumes:
         - /opt/persistance/grr/mysql:/var/lib/mysql
 env_file:
  - ./mysql.env
 ports:
  - 3306:3306


#GRR Container
grr:
 image: xalacaga/grr3
 container_name : grr3
 hostname: grr3
 ports:
  - 80:80
 links:
  - mysql:mysql
 volumes:
         - /opt/persistance/grr/html:/var/www/html/grr
 restart: always
